[package]
name             = "koth_ff_py"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
description      = "Python bindings for the koth_ff LC-MS feature finder"

[lib]
name = "koth_ff"
crate-type = ["cdylib"]

[dependencies]
koth_ff = { path = "../koth_ff", features = ["tdf"] }
pyo3    = { workspace = true }
